version: '3'

services:
  db:
    image: "postgres:12"
    restart: on-failure
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    restart: on-failure
    build: .
    command: python /web/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/web
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  postgres_data: