version: '3'

services:
  redis:
    image: "redis"
    restart: on-failure
    volumes:
      - redis_data:/data
  db:
    image: "postgres:12"
    restart: on-failure
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    restart: on-failure
    image: server_web
    build: .
    command: >
      sh -c "python /web/PusoyDosOnline/manage.py makemigrations PusoyDosServer &&
             python /web/PusoyDosOnline/manage.py migrate &&
             python /web/PusoyDosOnline/manage.py runworker game-manager lobby-clean &&
             python /web/PusoyDosOnline/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/web
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
    env_file:
      - .env

volumes:
  postgres_data:
  redis_data: